### ISSUE TITLE
why  mmcv cannot be installed？

### ISSUE THREAD

**Issue by Snnier** [linjing7/VR-Baseline#19]

**Comment by linjing7** [comment]
Hi, do you install mmcv following the instructions?
```
pip install openmim
mim install mmcv-full
```

**Comment by Snnier** [comment]
I keep getting num_works errors when running on google colab. I would like to ask where is the setting of this parameter?

**Comment by linjing7** [comment]
When you install mmcv-full with mim, it raise num_works error? You can try install mmcv-full from source following this [link](https://mmcv.readthedocs.io/en/latest/get_started/installation.html) .

**Comment by Snnier** [comment]
Ok, I’m trying

**Comment by Snnier** [comment]
Thank You !

**Comment by Snnier** [comment]
I use non-distributed training：python tools/train.py . But it's running with an error：RuntimeError: DataLoader worker (pid 2398) is killed by signal: Killed. on Google colab. why?

**Comment by linjing7** [comment]
Hi, this is because you do not have enough system memory. You need to apply for more system memory and CPU.

**Comment by Snnier** [comment]
I Know， thank you !

**Comment by Snnier** [comment]
Is it possible to reduce batch_size to reduce memory? But I can't find where to set batch_size. 
FGST_deblur_gopro_test.py, inside this file dict(type='PairedRandomCrop', gt_patch_size=16),  setting the size of gt_patch_size? Reduce memory？

**Comment by linjing7** [comment]
Hi, during inference, in order to save GPU memory and process a long video, we cache the image feature in the CPU. Thus, we need a large CPU memory. If you do not have enough CPU memory, you may try to train a smaller model with a smaller feature dimension by setting dim=16 in this [line](https://github.com/linjing7/VR-Baseline/blob/99611fb878962b1924ab1b15af170a3c3824e447/configs/FGST_deblur_gopro.py#L8C13-L8C13).

**Comment by Snnier** [comment]
OK ,thank you !
